CREATE TABLE IF NOT EXISTS `sys_customer_import_batches` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '导入批次ID',
  `tenant_id` int NOT NULL DEFAULT 0 COMMENT '租户ID',
  `user_id` int NOT NULL DEFAULT 0 COMMENT '导入用户ID',
  `dept_id` int NOT NULL DEFAULT 0 COMMENT '导入部门ID',
  `scene` varchar(20) NOT NULL DEFAULT 'my' COMMENT '导入场景',
  `channel_company_id` int NOT NULL DEFAULT 0 COMMENT '渠道公司ID',
  `channel_id` int NOT NULL DEFAULT 0 COMMENT '渠道主表ID',
  `channel_key` varchar(100) NOT NULL DEFAULT '' COMMENT '渠道编码',
  `channel_name` varchar(150) NOT NULL DEFAULT '' COMMENT '渠道展示名称',
  `file_affix_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT '导入文件附件ID',
  `file_name` varchar(255) NOT NULL DEFAULT '' COMMENT '导入文件名',
  `file_url` varchar(255) NOT NULL DEFAULT '' COMMENT '导入文件URL',
  `file_path` varchar(255) NOT NULL DEFAULT '' COMMENT '导入文件存储路径',
  `file_deleted_at` datetime(3) DEFAULT NULL COMMENT '导入文件清理时间',
  `total_count` int NOT NULL DEFAULT 0 COMMENT '总行数',
  `success_count` int NOT NULL DEFAULT 0 COMMENT '成功行数',
  `failed_count` int NOT NULL DEFAULT 0 COMMENT '失败行数',
  `status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT '导入状态',
  `error_message` varchar(1000) NOT NULL DEFAULT '' COMMENT '失败原因',
  `created_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` datetime(3) DEFAULT NULL COMMENT '删除时间',
  PRIMARY KEY (`id`),
  KEY `idx_customer_import_batch_tenant_created` (`tenant_id`, `created_at`),
  KEY `idx_customer_import_batch_tenant_user` (`tenant_id`, `user_id`, `status`),
  KEY `idx_customer_import_batch_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客户导入批次表';
