CREATE TABLE IF NOT EXISTS `sys_customer_export_tasks` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '导出任务主键ID',
  `tenant_id` bigint unsigned NOT NULL COMMENT '租户ID',
  `user_id` bigint unsigned NOT NULL COMMENT '提交导出任务的用户ID',
  `biz_type` varchar(50) NOT NULL DEFAULT 'syscustomer' COMMENT '业务类型',
  `status` varchar(20) NOT NULL DEFAULT 'queued' COMMENT '任务状态',
  `request_json` longtext NOT NULL COMMENT '导出请求参数快照JSON',
  `snapshot_max_id` int NOT NULL DEFAULT 0 COMMENT '本次导出快照允许的最大客户ID',
  `total` bigint NOT NULL DEFAULT 0 COMMENT '预计导出总条数',
  `processed` bigint NOT NULL DEFAULT 0 COMMENT '已处理条数',
  `progress` int NOT NULL DEFAULT 0 COMMENT '任务进度百分比',
  `affix_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT '生成的附件ID',
  `file_name` varchar(255) NOT NULL DEFAULT '' COMMENT '导出文件名',
  `error_message` varchar(1000) NOT NULL DEFAULT '' COMMENT '失败原因',
  `started_at` datetime(3) DEFAULT NULL COMMENT '任务开始时间',
  `finished_at` datetime(3) DEFAULT NULL COMMENT '任务结束时间',
  `created_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT '创建时间',
  `updated_at` datetime(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT '更新时间',
  `deleted_at` datetime(3) DEFAULT NULL COMMENT '软删除时间',
  PRIMARY KEY (`id`),
  KEY `idx_customer_export_task_biz_status` (`biz_type`, `status`),
  KEY `idx_customer_export_task_tenant_status` (`tenant_id`, `status`),
  KEY `idx_customer_export_task_tenant_user_status` (`tenant_id`, `user_id`, `status`),
  KEY `idx_customer_export_task_created_at` (`created_at`),
  KEY `idx_customer_export_task_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='客户导出任务队列表';
